# Generated by Django 5.1.7 on 2025-03-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watermarkimage',
            old_name='output_image',
            new_name='watermarked_image',
        ),
        migrations.RemoveField(
            model_name='watermarkimage',
            name='watermark_text',
        ),
    ]
